### ISSUE TITLE
something useful i guess

### ISSUE THREAD

**Issue by ghost** [CallieOwO/madewithlove.cfg#1]
instead of commenting out stuff, you can just use aliases

an example for [bad connection](https://github.com/CallieOwO/madewithlove.cfg/blob/master/madewithlove.cfg#L13-L22) and [good connection](https://github.com/CallieOwO/madewithlove.cfg/blob/master/madewithlove.cfg#L8-L11) ( can be replaced with ragdolls and gibs for example )

`alias "bad_connection"                             
"cl_cmdrate 40; cl_interp 0; cl_interp_ratio 2; cl_lagcompensation 1; cl_pred_optimize 2; cl_smooth 0; cl_smoothtime 0.01; cl_updaterate 40; rate 35000"`

`alias "good_connection"                             
"cl_cmdrate 66; cl_interp 0.01; rate 60000"`

but then again i'm not entirely sure if you need to either reconnect to the server or restart the game for these to have an effect.

**Comment by Mia0013** [comment]
I'll look into this, but as far as I know it would make things much less optimal due to the user needing to enter the aliases every time they launch the game.

**Comment by gulu-gulu** [comment]
> I'll look into this, but as far as I know it would make things much less optimal due to the user needing to enter the aliases every time they launch the game.

lets say you will enter an alias like `ragdoll_on`, the game uses the cvars and the values you've entered. now if you quit the game and enter again, the cvars should stay the same. i think if you add `host_writeconfig` at the end of the alias, it will overwrite the cvars in `config.cfg` which gets loaded by default iirc.

**Comment by Mia0013** [comment]
I see, I didn't get the entire idea at first. Still though I'm unsure whether it would improve anything as with how things are, the config is technically out of the box as long as the user doesn't need any changes made to it, with aliases the user would have to enter all of their preferences when they start the game up which is much more time consuming. I really like the idea though and I will look into it with Callie when I have time. Thanks.

**Comment by Mia0013** [comment]
Aliases have been added on the experimental branch.
